PATCH http://localhost:3001/api/my/account
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFydGFwcC50aGVvQGdtYWlsLmNvbSIsImlhdCI6MTcwODM2Nzc1OCwiZXhwIjoxNzA5NTc3MzU4fQ.iN1ZMMADNGGy7HtUrR5ZE3GrU2nhD07LYnyU3AtxN_E
Content-Type: application/json

{
  "name": "Maxence",
  "password": "mdptest"
}

###

GET http://localhost:3001/api/my/badges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFydGFwcC50aGVvQGdtYWlsLmNvbSIsImlhdCI6MTcwODM2Nzc1OCwiZXhwIjoxNzA5NTc3MzU4fQ.iN1ZMMADNGGy7HtUrR5ZE3GrU2nhD07LYnyU3AtxN_E

###

GET http://localhost:3001/api/my/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFydGFwcC50aGVvQGdtYWlsLmNvbSIsImlhdCI6MTcwODM2Nzc1OCwiZXhwIjoxNzA5NTc3MzU4fQ.iN1ZMMADNGGy7HtUrR5ZE3GrU2nhD07LYnyU3AtxN_E
###

POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
  "name": "Théo",
  "email": "artapp.theo@gmail.com",
  "password": "mdptest",
  "age": 16,
  "flami": 0,
  "badges": [],
  "metadata": {
    "favorite_sport": "Basketball",
    "origin": "Internet",
    "intent": "Other"
  },
  "otp": "354993"
}

###

POST http://localhost:3001/api/auth/signin
Content-Type: application/json

{
  "email": "artapp.theo@gmail.com",
  "password": "1234",
  "otp": "925034"
}

###

POST http://localhost:3001/api/auth/send-otp
Content-Type: application/json

{
  "email": "artapp.theo@gmail.com"
}

###

POST http://localhost:3001/api/auth/forget-password
Content-Type: application/json

{
  "email": "artapp.theo@gmail.com"
}

####

POST http://localhost:3001/api/auth/reset-password/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQzYzkyZjEzMTJhNDY3YzMzMTcyMTYiLCJpYXQiOjE3MDgzODQ2OTgsImV4cCI6MTcwODM4NTI5OH0.W-92lXMFsRU3LI4hWR8snENw2E8jaDgyzFl-2H9VXfY
Content-Type: application/json

{
  "password": "1234"
}